### ISSUE TITLE
Replace all instances of iwgcna/iWGCNA/IWGCNA with iterativeWGCNA

### ISSUE THREAD

**Issue by jpcartailler** [cstoeckert/iterativeWGCNA#2]
IWGCNA already exists (http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2625353/) and Emily has minted iterativeWGCNA as the appropriate name for this project/code. So, update all code/documentation to reflect this.

**Comment by fossilfriend** [comment]
done with merge from 'devel_1.0.0.RC' branch
