### ISSUE TITLE
 libopenblas.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by tiramisutes** [cstoeckert/iterativeWGCNA#20]
I get follows error when running ``python run_iterative_wgcna.py -h`` on the CentOS Linux platform:
```
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```
How to solve this question?
Thanks.

**Comment by fossilfriend** [comment]
iterativeWGCNA is written in Python but has dependencies on R and the rpy2 Python-R interface that both rely on C libraries.  I'd be happy to try and help you work through this issue but will need a more complete stack trace so we can see what/who is dependent in on that library.
