### ISSUE TITLE
[Question] Examples on using iterativeWGCNA to clean up blockwise modules?

### ISSUE THREAD

**Issue by jolespin** [cstoeckert/iterativeWGCNA#23]
I would like to run this in a Jupyter Notebook.  Do you have any examples of its usage in an interactive environment for refining blockwise modules of a large dataset?

**Comment by jpcartailler** [comment]
Emily had suggested to me several months ago to work out a Jupyter notebook for iterativeWGCNA. So here is what I have (out of the office right now, so may have something better back at work):

- Jupyter notebook (use this) - https://gist.github.com/c5creative/d6f72c13543bd59051747eabbd210af0
- Jupyter notebook, executed (for reference) - https://gist.github.com/c5creative/9690dda0bbe6ea477db81b6cc745cf7b
- Set up within Anaconda2 (easier to manage Python and R dependencies) - see my environment via https://gist.github.com/c5creative/97c7a98244d34f6226a7f817a549fee2
- Data is from DREAM5 - it's too large to post as a Gist and I'm not sure if there's any distribution restrictions, but I think it's available at https://www.synapse.org/#!Synapse:syn2787226. If needed, we can arrange a transfer.

I can't vouch for this working with a large dataset, having never tried it and not being anything more than a Jupyter neophyte. In any case, I hope this provides you with a starting point. Good luck!

JP
