### ISSUE TITLE
heatmap?

### ISSUE THREAD

**Issue by gudeqing** [cstoeckert/iterativeWGCNA#24]
I am really confused:
I found no heatmap or cluster tree graphs in output files. 
No examples found for drawing graphs like the standard wgcna pipeline do.

**Comment by cstoeckert** [comment]
Currently iterativeWGCNA does not generate any graphics but you can import the output files or saved block .RData files into R and use R & WGCNA to generate graphics.

**Comment by wangjiawen2013** [comment]
Dear,
how to generate images similar to plotNetworkHeatmap() in WGCNA  R package ?
![1](https://user-images.githubusercontent.com/29703450/60327328-1fed6b80-99be-11e9-9a41-283a04338c5b.png)
