### ISSUE TITLE
Problems reading the input file

### ISSUE THREAD

**Issue by jcabanad** [cstoeckert/iterativeWGCNA#34]
Hi!

Thank you very much for such an amazing tool. I'm trying to use it for my data and I have problems reading the input file. I have a .txt file with one row per gene and one column per sample, as it is described in the code. It can read the file and detect properly the number of genes, however, when I run the software it say that there are 0 samples.

This is the command I'm using

python run_iterative_wgcna.py -i /home/juditc/ADHD/GWAS_TDAH/TDAH/WGCNA/iterativeWGCNA/data_WGCNA_micro/datExpr_trans.txt --wgcnaParameters maxBlockSize=20000,corType=bicor,power=4,minModuleSize=30,saveTOMs=FALSE,minKMEtoStay=0.8,minCoreKME=0.8,networkType=signed,numericLabels=TRUE -o /home/juditc/ADHD/GWAS_TDAH/TDAH/WGCNA/iterativeWGCNA/results_WGCNA_micr/ -v

this is how my expression file look like:

gene CNT0004 CNT0005 CNT0006 CNT0008 CNT0009 CNT0010 CNT0011 CNT0013 CNT0015 
7896759 4.87840123385933 5.38352783819666 5.27055629800665 5.03304817148139 
7896761 3.52810116520177 3.64393642429303 3.70436640713184 3.90670441357473 
7896779 4.45185105685781 4.35454380046519 4.54187108060689 4.69967854721333

Best regards,

Judit

**Comment by fossilfriend** [comment]
Judit-

I am sorry to hear you are having issues reading your input file.  Is your file tab- or space-delimited? Currently iterativeWGCNA only handles [tab-delimited input](https://github.com/cstoeckert/iterativeWGCNA#input-file-format).

-Emily

**Comment by jcabanad** [comment]
Hi Emily,

I have double checked the file and I had a problem with the separators as you suggested. Sorry for the incovenience.

Best,

Judit
